name: Security Scan

on:
  schedule:
    - cron: '0 0 * * *'  # every midnight

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install pip-audit
        run: pip install pip-audit

      - name: Run security audit
        run: pip-audit
